services:
  django:
    container_name: django
    build:
      context: .
    command: uvicorn app.asgi:application --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./env_vars_django.txt
    depends_on:
      - redis
      - rabbitmq

  celery:
    container_name: celery
    build:
      context: .
    command: celery -A app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - ./env_vars_django.txt
    depends_on:
      - redis
      - rabbitmq

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

  flower:
    image: mher/flower
    restart: always
    container_name: flower
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
