services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # Expose Django on port 8000
      - "6380:6379"  # Expose Redis port (optional)
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
