services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000" # Django server
      - "6379" # Redis port for debugging or other usage
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - CELERY_BROKER_URL=redis://redis:6379/0 # Use 'redis' service name
    depends_on:
      - redis # Ensure Redis starts before the Django app
    command: [ "/entrypoint.sh" ] # Point to entrypoint script

  redis:
    image: redis:6.2 # Redis image
    container_name: redis
    ports:
      - "6379" # Expose Redis port for communication
