services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/user/src/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - DJANGO_SETTINGS_MODULE=app.settings
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
  celery:
    build: .
    container_name: celery
    command: celery -A app worker --loglevel=info
    volumes:
      - .:/user/src/app
    depends_on:
      - django
      - redis
  redis:
    image: redis:latest
    container_name: redis
