# Generated by Django 5.1.4 on 2024-12-29 16:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload_data', models.JSONField(verbose_name='Dados do Payload')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Beneficiário')),
                ('id_card', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator('^\\d{17}$', 'A carteirinha deve conter exatos 17 dígitos.')], verbose_name='Carteirinha')),
                ('type', models.CharField(choices=[('6', 'Atendimento Domiciliar'), ('4', 'Consulta'), ('23', 'Exame'), ('5', 'Exame Ambulatorial'), ('7', 'Internação (SADT internado)'), ('3', 'Outras Terapias'), ('2', 'Pequena Cirurgia'), ('13', 'Pequeno Atendimento (sutura, gesso e outros)'), ('11', 'Pronto Socorro'), ('8', 'Quimioterapia'), ('9', 'Radioterapia'), ('1', 'Remoção'), ('14', 'Saúde Ocupacional - Admissional'), ('21', 'Saúde Ocupacional - Assistência a Demitidos'), ('20', 'Saúde Ocupacional - Beneficiário Novo'), ('15', 'Saúde Ocupacional - Demissional'), ('18', 'Saúde Ocupacional - Mudança de Função'), ('16', 'Saúde Ocupacional - Periódico'), ('19', 'Saúde Ocupacional - Promoção à Saúde'), ('17', 'Saúde Ocupacional - Retorno ao Trabalho'), ('22', 'Telessaúde'), ('10', 'Terapia Renal Substitutiva (TRS)')], max_length=2, verbose_name='Tipo de Atendimento')),
                ('qtd', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade a Executar')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnimedCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=255, verbose_name='Unimed Login')),
                ('password', models.CharField(max_length=255, verbose_name='Unimed Password')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
