# Generated by Django 5.1.4 on 2024-12-29 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_clientmodel_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='id_card',
            new_name='codigo_beneficiario',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='nome_beneficiario',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='qtd',
            new_name='quantidade',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='type',
            new_name='tipo_atendimento',
        ),
    ]
